apiVersion: v1
kind: Pod
metadata:
  name: adapter-example
  namespace: default
  labels:
    app: adapter-example
spec:
  containers:
    - image: redis:latest
      name: redis
    - image: oliver006/redis_exporter:latest
      name: adapter
